# Generated by Django 3.1.3 on 2021-11-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20211126_2203'),
        ('core', '0002_auto_20211127_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_LoanAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.CharField(max_length=13, unique=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('ClientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.tbl_clients')),
            ],
        ),
    ]
