# Generated by Django 3.1.3 on 2021-11-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20211126_2203'),
        ('core', '0003_tbl_loanaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_loanaccounts',
            name='ClientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.tbl_clients', unique=True),
        ),
    ]
