# Generated by Django 3.1.3 on 2021-11-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_clients',
            name='AccountNumber',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
