# Generated by Django 3.1.3 on 2021-11-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_tbl_clients_accountnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_clients',
            options={'verbose_name': 'tbl_Client', 'verbose_name_plural': 'tbl_Clients'},
        ),
        migrations.AddField(
            model_name='tbl_clients',
            name='Address',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
