# Generated by Django 3.1.3 on 2021-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20211126_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_clients',
            name='AmountEligible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, max_length=12),
            preserve_default=False,
        ),
    ]
