# Generated by Django 3.1.3 on 2021-11-28 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_tbl_clients_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_clients',
            name='Username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
