# Generated by Django 3.1.3 on 2022-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20211128_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_clients',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
