# Generated by Django 3.1.3 on 2022-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20220102_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_clients',
            name='AccountNumber',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='AmountEligible',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='ClientType',
            field=models.CharField(choices=[('C', 'Client'), ('L', 'Lender'), ('S', 'Service provider')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='national_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
