# Generated by Django 3.1.3 on 2022-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20220102_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_clients',
            name='AccountNumber',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_clients',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
